import type { Template, RecommendedTemplateFields, PopularTemplateFields } from './template.types';

export const mockRecommendedTemplates: RecommendedTemplateFields[] = [
  {
    templateId: 1,
    type: 'recommended',
    title: '제주도 힐링 여행 3박 4일',
    coverImageUrl: 'https://images.unsplash.com/photo-1544644181-1484b3fdfc62?q=80&w=2088&auto=format&fit=crop',
    travelTheme: '힐링',
    description: '푸른 바다와 오름을 거니는 진정한 휴식',
    region: '제주도',
    tripDays: '3박 4일',
  },
  {
    templateId: 2,
    type: 'recommended',
    title: '부산 맛집 완전 정복',
    coverImageUrl: 'https://images.unsplash.com/photo-1544644181-1484b3fdfc62?q=80&w=2088&auto=format&fit=crop',
    travelTheme: '맛집',
    description: '로컬이 추천하는 찐 맛집 탐방기',
    region: '부산',
    tripDays: '2박 3일',
  },
  {
    templateId: 3,
    type: 'recommended',
    title: '경주 역사 문화 탐방',
    coverImageUrl: 'https://images.unsplash.com/photo-1544644181-1484b3fdfc62?q=80&w=2088&auto=format&fit=crop',
    travelTheme: '문화',
    description: '천 년의 역사가 살아 숨쉬는 경주 여행',
    region: '경주',
    tripDays: '1박 2일',
  },
  {
    templateId: 4,
    type: 'recommended',
    title: '설악산 자연 트레킹',
    coverImageUrl: 'https://images.unsplash.com/photo-1544644181-1484b3fdfc62?q=80&w=2088&auto=format&fit=crop',
    travelTheme: '자연',
    description: '단풍과 계곡이 어우러진 가을 산행',
    region: '속초',
    tripDays: '2박 3일',
  },
  {
    templateId: 5,
    type: 'recommended',
    title: '전주 한옥마을 문화체험',
    coverImageUrl: 'https://images.unsplash.com/photo-1544644181-1484b3fdfc62?q=80&w=2088&auto=format&fit=crop',
    travelTheme: '문화',
    description: '한복 입고 걷는 전통의 거리',
    region: '전주',
    tripDays: '1박 2일',
  },
  {
    templateId: 6,
    type: 'recommended',
    title: '강릉 바다 힐링 투어',
    coverImageUrl: 'https://images.unsplash.com/photo-1544644181-1484b3fdfc62?q=80&w=2088&auto=format&fit=crop',
    travelTheme: '힐링',
    description: '커피 한 잔과 함께하는 동해 바다',
    region: '강릉',
    tripDays: '2박 3일',
  },
  {
    templateId: 7,
    type: 'recommended',
    title: '여수 낭만 야경 투어',
    coverImageUrl: 'https://images.unsplash.com/photo-1544644181-1484b3fdfc62?q=80&w=2088&auto=format&fit=crop',
    travelTheme: '로컬',
    description: '반짝이는 밤바다와 케이블카',
    region: '여수',
    tripDays: '2박 3일',
  },
  {
    templateId: 8,
    type: 'recommended',
    title: '양양 서핑 액티비티',
    coverImageUrl: 'https://images.unsplash.com/photo-1544644181-1484b3fdfc62?q=80&w=2088&auto=format&fit=crop',
    travelTheme: '액티비티',
    description: '파도를 타며 즐기는 여름 바캉스',
    region: '양양',
    tripDays: '3박 4일',
  },
  {
    templateId: 9,
    type: 'recommended',
    title: '통영 해산물 맛집 투어',
    coverImageUrl: 'https://images.unsplash.com/photo-1544644181-1484b3fdfc62?q=80&w=2088&auto=format&fit=crop',
    travelTheme: '맛집',
    description: '싱싱한 해산물과 케이블카 여행',
    region: '통영',
    tripDays: '1박 2일',
  },
  {
    templateId: 10,
    type: 'recommended',
    title: '남이섬 자연 산책',
    coverImageUrl: 'https://images.unsplash.com/photo-1544644181-1484b3fdfc62?q=80&w=2088&auto=format&fit=crop',
    travelTheme: '자연',
    description: '메타세쿼이아 길을 걷는 힐링 여행',
    region: '춘천',
    tripDays: '당일',
  },
];

export const mockPopularTemplates: PopularTemplateFields[] = [
  {
    templateId: 101,
    type: 'popular',
    title: '성수동 힙플레이스 투어',
    coverImageUrl: 'https://images.unsplash.com/photo-1544644181-1484b3fdfc62?q=80&w=2088&auto=format&fit=crop',
    travelTheme: '로컬',
    tag: '#카페 #팝업스토어',
    authorName: '힙스터김',
    avgRating: 4.8,
    starCount: 124,
    remixCount: 56,
  },
  {
    templateId: 102,
    type: 'popular',
    title: '강릉 바다와 커피 한 잔',
    coverImageUrl: 'https://images.unsplash.com/photo-1544644181-1484b3fdfc62?q=80&w=2088&auto=format&fit=crop',
    travelTheme: '힐링',
    tag: '#오션뷰 #커피거리',
    authorName: '여행조아',
    avgRating: 4.9,
    starCount: 231,
    remixCount: 89,
  },
  {
    templateId: 103,
    type: 'popular',
    title: '전주 한옥마을 먹방',
    coverImageUrl: 'https://images.unsplash.com/photo-1544644181-1484b3fdfc62?q=80&w=2088&auto=format&fit=crop',
    travelTheme: '맛집',
    tag: '#길거리음식 #한복',
    authorName: '먹깨비',
    avgRating: 4.7,
    starCount: 198,
    remixCount: 42,
  },
  {
    templateId: 104,
    type: 'popular',
    title: '양양 서핑 & 풀파티',
    coverImageUrl: 'https://images.unsplash.com/photo-1544644181-1484b3fdfc62?q=80&w=2088&auto=format&fit=crop',
    travelTheme: '액티비티',
    tag: '#서핑 #여름',
    authorName: '파도타고',
    avgRating: 4.6,
    starCount: 85,
    remixCount: 30,
  },
  {
    templateId: 105,
    type: 'popular',
    title: '제주 숨은 명소 탐방',
    coverImageUrl: 'https://images.unsplash.com/photo-1544644181-1484b3fdfc62?q=80&w=2088&auto=format&fit=crop',
    travelTheme: '자연',
    tag: '#비밀장소 #오름',
    authorName: '제주러버',
    avgRating: 4.9,
    starCount: 312,
    remixCount: 145,
  },
  {
    templateId: 106,
    type: 'popular',
    title: '부산 감천문화마을 산책',
    coverImageUrl: 'https://images.unsplash.com/photo-1544644181-1484b3fdfc62?q=80&w=2088&auto=format&fit=crop',
    travelTheme: '문화',
    tag: '#포토스팟 #예술',
    authorName: '사진작가이',
    avgRating: 4.5,
    starCount: 167,
    remixCount: 73,
  },
  {
    templateId: 107,
    type: 'popular',
    title: '속초 중앙시장 먹방 투어',
    coverImageUrl: 'https://images.unsplash.com/photo-1544644181-1484b3fdfc62?q=80&w=2088&auto=format&fit=crop',
    travelTheme: '맛집',
    tag: '#시장 #해산물',
    authorName: '맛집헌터',
    avgRating: 4.8,
    starCount: 203,
    remixCount: 91,
  },
  {
    templateId: 108,
    type: 'popular',
    title: '경복궁 야간 개장 투어',
    coverImageUrl: 'https://images.unsplash.com/photo-1544644181-1484b3fdfc62?q=80&w=2088&auto=format&fit=crop',
    travelTheme: '문화',
    tag: '#야경 #한복',
    authorName: '서울토박이',
    avgRating: 4.7,
    starCount: 156,
    remixCount: 68,
  },
  {
    templateId: 109,
    type: 'popular',
    title: '여수 밤바다 낭만 여행',
    coverImageUrl: 'https://images.unsplash.com/photo-1544644181-1484b3fdfc62?q=80&w=2088&auto=format&fit=crop',
    travelTheme: '로컬',
    tag: '#야경 #케이블카',
    authorName: '낭만주의자',
    avgRating: 4.9,
    starCount: 278,
    remixCount: 112,
  },
  {
    templateId: 110,
    type: 'popular',
    title: '설악산 단풍 트레킹',
    coverImageUrl: 'https://images.unsplash.com/photo-1544644181-1484b3fdfc62?q=80&w=2088&auto=format&fit=crop',
    travelTheme: '자연',
    tag: '#등산 #단풍',
    authorName: '산악인박',
    avgRating: 4.8,
    starCount: 189,
    remixCount: 77,
  },
];

export const mockTemplates: Template[] = [...mockRecommendedTemplates, ...mockPopularTemplates];
